version: "3.7"

services:
 
  db: 
    image: postgres
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: sales
    volumes:
      - ./pgdata:/var/lib/postgres/data
    ports:
      - 5432:5432

  flask: 
    build: ./flask
    container_name: flask
    depends_on:
      - db
    environment:
      - APP_NAME=MyFlaskApp
    volumes:
      - ./flask:/usr/src/app
    ports:
      - 6001:6000

    command: ["./wait-for-it.sh", "db:5432", "--", "python", "api_service.py"]

     


